import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import EmailPopup from "@/components/EmailPopup";
import ExitIntentPopup from "@/components/ExitIntentPopup";
import { CartProvider } from "@/context/CartContext";
import CartSidebar from "@/components/CartSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <CartProvider>
          {children}
          <CartSidebar />
        </CartProvider>
        <EmailPopup />
        <ExitIntentPopup
          calendlyLink="https://calendly.com/ederod-handpan"
          phoneNumber="+33123456789"
        />
      </body>
    </html>
  );
}
